name: crypto_tracker
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  app_settings: ^5.1.1
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  dio: ^5.7.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^4.2.1
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  go_router: ^14.6.3
  injectable: ^2.5.0
  lottie: ^3.3.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.8.1

  isar:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs: # contains Isar Core
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/
  path_provider: ^2.1.5
dev_dependencies:
  analyzer: ^6.11.0
  build_runner:
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.4.0
  injectable_generator: ^2.4.1
  retrofit_generator: ^9.1.7
  isar_generator:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    # - assets/svg/
    - assets/json/

  fonts:
    - family: CairoFont
      fonts:
        - asset: assets/fonts/Cairo/TTF/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Cairo/TTF/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo/TTF/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo/TTF/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo/TTF/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo/TTF/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo/TTF/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Cairo/TTF/Cairo-Black.ttf
          weight: 900
